trigger:
- main

pool:
 vmImage: ubuntu-latest

jobs:
  - job: Build
    steps:
      - script: 'pwd'
      - script: 'ls -l'
      - task: Docker@2
        inputs:
          containerRegistry: 'ajay_acr_con'
          repository: 'techtalk'
          command: 'buildAndPush'
          Dockerfile: '**/dockerfile'
          tags: $(Build.SourceVersion)
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: 'Microsoft Azure(1)(67aa1a6a-7473-46e2-aec6-d27892dfa9ba)'
          appName: 'techtaks'
          containers: 'techtalk:$(Build.SourceVersion)'
      
      